export const GET_CONVERSATIONS = 'GET_CONVERSATIONS'
export const GET_CURRENT_CHAT = 'GET_CURRENT_CHAT'
export const CREATE_MESSAGE = 'CREATE_MESSAGE'
export const CREATE_CONVERSATION = 'CREATE_CONVERSATION'